import Hero from "@components/organisms/Hero";
import Head from "next/head";
import Container from "@components/templates/Container";
import LinkComponent from "@components/atoms/LinkComponent";
import EndTitle from "@components/atoms/EndTitle";
import Experience from "@components/organisms/Experience";
import Footer from "@components/organisms/Footer";
import PostScriptum from "@components/organisms/PostScriptum";

const jobs = [
  {
    title: "Cobas Asset Management",
    href: "https://cobasam.com/",
    year: "22",
    roles: ["Full-Stack", "DigitalConsultancy", "DBA", "DataEngineering"],
    tech: ["NextJS", "React", "PostgreSQL", "MongoDB", "Azure DF"],
    more: "Design and coding of back-office applications.",
  },
  {
    title: "tagle.dev",
    href: "https://tagle.dev/",
    year: "21—22",
    roles: ["Owner", "Freelance"],
    tech: ["NextJS", "React", "Sanity", "Eleventy"],
    more: "It channels my freelance work.",
  },
  {
    title: "Claps Artificial Intelligence, Inc.",
    href: "https://claps.ai/",
    year: "21",
    roles: ["COO"],
    tech: ["Swift", "SwiftUI"],
    more: "+200K € raised in seed funding by Eneko Knorr & others.",
  },
  {
    title: "CMC Group (now acquired by CGI)",
    href: "https://www.cgi.com/",
    year: "19—21",
    roles: ["Digital Marketing", "Front-End"],
    tech: ["Eleventy", "JavaScript", "CSS", "SQL", "SageCRM"],
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-12 space-y-24">
        <Hero />
        <Experience props={jobs} />
        <PostScriptum />
      </main>
      <Footer />
    </div>
  );
}
