import Hero from "@components/organisms/Hero";
import Head from "next/head";


export default function Home() {
  return (
    <div className="cursor-ff2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
      </main>

      <footer></footer>
    </div>
  );
}
